version: '3'
services:
  grpc:
    container_name: grpc
    build:
      context: .
      dockerfile: ./service/Dockerfile
    ports:
      - "50051:50051"
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "8001:8001"
    links:
      - grpc